Fixed thread safety issue raised by infer
Move the thread unsafe access of charset inside synchronised block

------ Infer report ------------
app/src/main/java/org/connectbot/service/Relay.java:81: error: THREAD_SAFETY_VIOLATION
  Unprotected write. Non-private method `org.connectbot.service.Relay.setCharset` writes to field `&this.org.connectbot.service.Relay.currentCharset` outside of synchronization.
 Reporting because this access may occur on a background thread.
Showing all 1 steps of the trace

app/src/main/java/org/connectbot/service/Relay.java:81:-1: access to `&this.org.connectbot.service.Relay.currentCharset`
79.   		newCd.onMalformedInput(CodingErrorAction.REPLACE);
80.
81. > 		currentCharset = charset;
82.   		synchronized (this) {
83.   			decoder = newCd;

------------------------------------